fix: use a subshell

diff --git a/.github/workflows/continous-delivery.yml b/.github/workflows/continous-delivery.yml
--- a/.github/workflows/continous-delivery.yml
+++ b/.github/workflows/continous-delivery.yml
@@ -136,25 +136,26 @@ jobs:
         run: |
           docker pull ${{ vars.GAR_BASE }}/zebrad@${{ needs.build.outputs.image_digest }}
           docker run --detach --name default-conf-tests -t ${{ vars.GAR_BASE }}/zebrad@${{ needs.build.outputs.image_digest }}
-          trap "" PIPE;
-          # Temporarily disable "set -e" to handle the broken pipe error gracefully
-          set +e;
-          docker logs \
-          --tail all \
-          --follow \
-          default-conf-tests | \
-          tee --output-error=exit /dev/stderr | \
-          grep --max-count=1 --extended-regexp --color=always \
-          -e "net.*=.*Main.*estimated progress to chain tip.*BeforeOverwinter";
-          LOGS_EXIT_STATUS=$?;
-          set -e;
+
+          # Use a subshell to handle the broken pipe error gracefully
+          (
+            trap "" PIPE;
+            docker logs \
+            --tail all \
+            --follow \
+            default-conf-tests | \
+            tee --output-error=exit /dev/stderr | \
+            grep --max-count=1 --extended-regexp --color=always \
+            -e "net.*=.*Main.*estimated progress to chain tip.*BeforeOverwinter"
+          ) || true
+          LOGS_EXIT_STATUS=$?
 
           docker stop default-conf-tests
 
           EXIT_STATUS=$(docker wait default-conf-tests || echo "Error retrieving exit status");
           echo "docker exit status: $EXIT_STATUS";
 
-          # If grep found the pattern, exit with the Docker container"s exit status
+          # If grep found the pattern, exit with the Docker container exit status
           if [ $LOGS_EXIT_STATUS -eq 0 ]; then
               exit $EXIT_STATUS;
           fi
@@ -183,26 +184,26 @@ jobs:
         run: |
           docker pull ${{ vars.GAR_BASE }}/zebrad@${{ needs.build.outputs.image_digest }}
           docker run --env "NETWORK=Testnet" --detach --name testnet-conf-tests -t ${{ vars.GAR_BASE }}/zebrad@${{ needs.build.outputs.image_digest }}
-          trap "" PIPE;
-          # Temporarily disable "set -e" to handle the broken pipe error gracefully
-          set +e;
-          docker logs \
-          --tail all \
-          --follow \
-          testnet-conf-tests | \
-          tee --output-error=exit /dev/stderr | \
-          grep --max-count=1 --extended-regexp --color=always \
-          -e "net.*=.*Test.*estimated progress to chain tip.*Genesis" \
-          -e "net.*=.*Test.*estimated progress to chain tip.*BeforeOverwinter";
-          LOGS_EXIT_STATUS=$?;
-          set -e;
+          # Use a subshell to handle the broken pipe error gracefully
+          (
+            trap "" PIPE;
+            docker logs \
+            --tail all \
+            --follow \
+            testnet-conf-tests | \
+            tee --output-error=exit /dev/stderr | \
+            grep --max-count=1 --extended-regexp --color=always \
+            -e "net.*=.*Test.*estimated progress to chain tip.*Genesis" \
+            -e "net.*=.*Test.*estimated progress to chain tip.*BeforeOverwinter";
+          ) || true
+          LOGS_EXIT_STATUS=$?
 
           docker stop testnet-conf-tests
 
           EXIT_STATUS=$(docker wait testnet-conf-tests || echo "Error retrieving exit status");
           echo "docker exit status: $EXIT_STATUS";
 
-          # If grep found the pattern, exit with the Docker container"s exit status
+          # If grep found the pattern, exit with the Docker container exit status
           if [ $LOGS_EXIT_STATUS -eq 0 ]; then
               exit $EXIT_STATUS;
           fi
