chore: fix variable substitution

diff --git a/.github/workflows/sub-deploy-integration-tests-gcp.yml b/.github/workflows/sub-deploy-integration-tests-gcp.yml
--- a/.github/workflows/sub-deploy-integration-tests-gcp.yml
+++ b/.github/workflows/sub-deploy-integration-tests-gcp.yml
@@ -308,37 +308,33 @@ jobs:
           --ssh-flag="-o ServerAliveInterval=5" \
           --ssh-flag="-o ConnectionAttempts=20" \
           --ssh-flag="-o ConnectTimeout=5" \
-          --command=' \
-          echo "Streaming logs and waiting for test success message..."; \
-          sudo docker logs \
-          --tail all \
-          --follow \
-          ${CONTAINER_ID} \
-          | tee --output-error=exit-nopipe /dev/stderr \
-          | grep --max-count=1 --extended-regexp --color=always \
-          "test result: .*ok.* [1-9][0-9]* passed.*finished in";
-          LOGS_EXIT_STATUS=$?;
-          echo "Waiting for container ${CONTAINER_ID} to exit...";
-          EXIT_STATUS=$(sudo docker wait ${CONTAINER_ID} || echo "Error retrieving exit status");
-          echo "Container exit status: $EXIT_STATUS";
+          --command="
+          echo 'Streaming logs and waiting for test success message...';
+          sudo docker logs
+          --tail all
+          --follow
+          ${CONTAINER_ID}
+          | tee --output-error=exit-nopipe /dev/stderr
+          | grep --max-count=1 --extended-regexp --color=always
+          'test result: .*ok.* [1-9][0-9]* passed.*finished in';
+          LOGS_EXIT_STATUS=\$?;
+          echo 'Waiting for container ${CONTAINER_ID} to exit...';
+          EXIT_STATUS=\$(sudo docker wait ${CONTAINER_ID} || echo 'Error retrieving exit status');
+          echo 'Container exit status: '\$EXIT_STATUS;
 
-          if [ $LOGS_EXIT_STATUS -ne 0 ]; then
-            # Grep failed (pattern not found)
-            echo "Test failed: Success log pattern not found (grep exit status: $LOGS_EXIT_STATUS).";
+          if [ \$LOGS_EXIT_STATUS -ne 0 ]; then
+            echo 'Test failed: Success log pattern not found (grep exit status: '\$LOGS_EXIT_STATUS').';
             exit 1;
           else
-            # Grep succeeded (pattern found), now check specific exit code
-            if [ "$EXIT_STATUS" -eq 1 ]; then
-              # Explicit failure code 1
-              echo "Test failed: Success log pattern found BUT container exited with status 1.";
+            if [ \"\$EXIT_STATUS\" -eq 1 ]; then
+              echo 'Test failed: Success log pattern found BUT container exited with status 1.';
               exit 1;
             else
-              # Grep succeeded and exit status is not 1
-              echo "Test successful: Success log pattern found. Container exit status $EXIT_STATUS ignored (as it is not 1).";
+              echo 'Test successful: Success log pattern found. Container exit status '\$EXIT_STATUS' ignored (as it is not 1).';
               exit 0;
             fi
-          fi \
-          '
+          fi
+          "
 
   # create a state image from the instance's state disk, if requested by the caller
   create-state-image:
